# SPDX-License-Identifier: GPL-2.0-or-later
# GradientBasedLearningForCAP: Gradient Based Learning via Category Theory
#
# Declarations
#
# THIS FILE IS AUTOMATICALLY GENERATED, SEE CAP_project/CAP/gap/MethodRecord.gi

#! @Chapter Category of Lenses

#! @Section Supported CAP Operations

#! @Subsection Category of Lenses of Smooth Maps

#! The following CAP operations are supported:
#! * <Ref BookName="MonoidalCategories" Func="AssociatorLeftToRight" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="AssociatorLeftToRightWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="AssociatorRightToLeft" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="AssociatorRightToLeftWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="Braiding" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="BraidingInverse" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="BraidingInverseWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="BraidingWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="CAP" Func="IdentityMorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEndomorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualForObjects" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForMorphismsWithGivenSourceAndRange" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForObjects" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="LeftUnitor" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="LeftUnitorInverse" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="LeftUnitorInverseWithGivenTensorProduct" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="LeftUnitorWithGivenTensorProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="MorphismConstructor" Label="for Is" />
#! * <Ref BookName="CAP" Func="MorphismDatum" Label="for Is" />
#! * <Ref BookName="CAP" Func="ObjectConstructor" Label="for Is" />
#! * <Ref BookName="CAP" Func="ObjectDatum" Label="for Is" />
#! * <Ref BookName="CAP" Func="PostCompose" Label="for Is" />
#! * <Ref BookName="CAP" Func="PostComposeList" Label="for Is" />
#! * <Ref BookName="CAP" Func="PreCompose" Label="for Is" />
#! * <Ref BookName="CAP" Func="PreComposeList" Label="for Is" />
#! * <Ref BookName="CAP" Func="RandomMorphismWithFixedSourceAndRangeByInteger" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="RightUnitor" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="RightUnitorInverse" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="RightUnitorInverseWithGivenTensorProduct" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="RightUnitorWithGivenTensorProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="SimplifyMorphism" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="TensorProductOnMorphisms" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="TensorProductOnMorphismsWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="TensorProductOnObjects" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="TensorUnit" Label="for Is" />
