# SPDX-License-Identifier: GPL-2.0-or-later
# GradientBasedLearningForCAP: Gradient Based Learning via Category Theory
#
# Declarations
#
# THIS FILE IS AUTOMATICALLY GENERATED, SEE CAP_project/CAP/gap/MethodRecord.gi

#! @Chapter Category of Parametrised Morphisms

#! @Section Supported CAP Operations

#! @Subsection Category of Parametrised Smooth Maps

#! The following CAP operations are supported:
#! * <Ref BookName="CAP" Func="IdentityMorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsCongruentForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEndomorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualForMorphismsOnMor" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualForObjects" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualToIdentityMorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsIdempotent" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsOne" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForMorphismsWithGivenSourceAndRange" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForObjects" Label="for Is" />
#! * <Ref BookName="CAP" Func="MorphismConstructor" Label="for Is" />
#! * <Ref BookName="CAP" Func="MorphismDatum" Label="for Is" />
#! * <Ref BookName="CAP" Func="ObjectConstructor" Label="for Is" />
#! * <Ref BookName="CAP" Func="ObjectDatum" Label="for Is" />
#! * <Ref BookName="CAP" Func="PostCompose" Label="for Is" />
#! * <Ref BookName="CAP" Func="PostComposeList" Label="for Is" />
#! * <Ref BookName="CAP" Func="PreCompose" Label="for Is" />
#! * <Ref BookName="CAP" Func="PreComposeList" Label="for Is" />
#! * <Ref BookName="CAP" Func="SimplifyMorphism" Label="for Is" />
