# SPDX-License-Identifier: GPL-2.0-or-later
# GradientBasedLearningForCAP: Gradient Based Learning via Category Theory
#
# Declarations
#
# THIS FILE IS AUTOMATICALLY GENERATED, SEE CAP_project/CAP/gap/MethodRecord.gi

#! @Chapter Skeletal Category of Smooth Maps

#! @Section Supported CAP Operations

#! @Subsection SkeletalSmoothMaps

#! The following CAP operations are supported:
#! * <Ref BookName="CAP" Func="AdditionForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="AdditiveInverseForMorphisms" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="AssociatorLeftToRight" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="AssociatorLeftToRightWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="AssociatorRightToLeft" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="AssociatorRightToLeftWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="Braiding" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="BraidingInverse" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="BraidingInverseWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="BraidingWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianAssociatorLeftToRight" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianAssociatorLeftToRightWithGivenDirectProducts" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianAssociatorRightToLeft" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianAssociatorRightToLeftWithGivenDirectProducts" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianBraiding" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianBraidingInverse" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianBraidingInverseWithGivenDirectProducts" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianBraidingWithGivenDirectProducts" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianDiagonal" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianDiagonalWithGivenCartesianPower" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianLeftUnitor" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianLeftUnitorInverse" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianLeftUnitorInverseWithGivenDirectProduct" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianLeftUnitorWithGivenDirectProduct" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianRightUnitor" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianRightUnitorInverse" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianRightUnitorInverseWithGivenDirectProduct" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="CartesianRightUnitorWithGivenDirectProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="ComponentOfMorphismIntoDirectProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="DirectProduct" Label="" />
#! * <Ref BookName="CAP" Func="DirectProductFunctorial" Label="for Is" />
#! * <Ref BookName="CAP" Func="DirectProductFunctorialWithGivenDirectProducts" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="DirectProductOnMorphisms" Label="for Is" />
#! * <Ref BookName="CartesianCategories" Func="DirectProductOnMorphismsWithGivenDirectProducts" Label="for Is" />
#! * <Ref BookName="CAP" Func="IdentityMorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsCongruentForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEndomorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualForMorphismsOnMor" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualForObjects" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualToIdentityMorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsEqualToZeroMorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsIdempotent" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsOne" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsTerminal" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForMorphismsWithGivenSourceAndRange" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsWellDefinedForObjects" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsZeroForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="IsZeroForObjects" Label="for Is" />
#! * <Ref BookName="CAP" Func="JointPairwiseDifferencesOfMorphismsIntoDirectProduct" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="LeftUnitor" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="LeftUnitorInverse" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="LeftUnitorInverseWithGivenTensorProduct" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="LeftUnitorWithGivenTensorProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="LinearCombinationOfMorphisms" Label="for Is" />
#! * <Ref BookName="ToolsForCategoricalTowers" Func="MorphismBetweenDirectProducts" Label="for Is" />
#! * <Ref BookName="ToolsForCategoricalTowers" Func="MorphismBetweenDirectProductsWithGivenDirectProducts" Label="for Is" />
#! * <Ref BookName="CAP" Func="MorphismConstructor" Label="for Is" />
#! * <Ref BookName="CAP" Func="MorphismDatum" Label="for Is" />
#! * <Ref BookName="GradientBasedLearningForCAP" Func="MultiplicationForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="MultiplyWithElementOfCommutativeRingForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="ObjectConstructor" Label="for Is" />
#! * <Ref BookName="CAP" Func="ObjectDatum" Label="for Is" />
#! * <Ref BookName="CAP" Func="PostCompose" Label="for Is" />
#! * <Ref BookName="CAP" Func="PostComposeList" Label="for Is" />
#! * <Ref BookName="CAP" Func="PreCompose" Label="for Is" />
#! * <Ref BookName="CAP" Func="PreComposeList" Label="for Is" />
#! * <Ref BookName="CAP" Func="ProjectionInFactorOfDirectProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="ProjectionInFactorOfDirectProductWithGivenDirectProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="RandomMorphismWithFixedSourceAndRangeByInteger" Label="for Is" />
#! * <Ref BookName="GradientBasedLearningForCAP" Func="ReverseDifferential" Label="for Is" />
#! * <Ref BookName="GradientBasedLearningForCAP" Func="ReverseDifferentialWithGivenObjects" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="RightUnitor" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="RightUnitorInverse" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="RightUnitorInverseWithGivenTensorProduct" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="RightUnitorWithGivenTensorProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="SimplifyMorphism" Label="for Is" />
#! * <Ref BookName="CAP" Func="SubtractionForMorphisms" Label="for Is" />
#! * <Ref BookName="CAP" Func="SumOfMorphisms" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="TensorProductOnMorphisms" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="TensorProductOnMorphismsWithGivenTensorProducts" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="TensorProductOnObjects" Label="for Is" />
#! * <Ref BookName="MonoidalCategories" Func="TensorUnit" Label="for Is" />
#! * <Ref BookName="CAP" Func="TerminalObject" Label="for Is" />
#! * <Ref BookName="CAP" Func="TerminalObjectFunctorial" Label="for Is" />
#! * <Ref BookName="CAP" Func="TerminalObjectFunctorialWithGivenTerminalObjects" Label="for Is" />
#! * <Ref BookName="CAP" Func="UniversalMorphismIntoDirectProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="UniversalMorphismIntoDirectProductWithGivenDirectProduct" Label="for Is" />
#! * <Ref BookName="CAP" Func="UniversalMorphismIntoTerminalObject" Label="for Is" />
#! * <Ref BookName="CAP" Func="UniversalMorphismIntoTerminalObjectWithGivenTerminalObject" Label="for Is" />
#! * <Ref BookName="CAP" Func="ZeroMorphism" Label="for Is" />
